### ISSUE TITLE
Using the default region provider chain

### ISSUE THREAD

**Issue by singhbaljit** [awslabs/aws-glue-schema-registry#279]
The region property is required using `AWSSchemaRegistryConstants.AWS_REGION`. However, AWS SDKs (both v1 and v2) provide a default region provider chain. Can the SerDes classes not select the region based on the chain? `AWSSchemaRegistryConstants.AWS_REGION` can still serve as override instead of being required. This also maintains backwards compatibility.

**Comment by blacktooth** [comment]
This is a good enhancement. 

Here are my thoughts,

1. We need to carefully think about the backward compatibility of this. 
2. [AWS SDK documentation](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html) suggests that it will fail when the region couldn't be found. We need to make sure that error is caught and thrown as `AWSSchemaRegistryException` as we do today if `AWS_REGION` is missing.
3. We need to make sure the `AWSSchemaRegistryConstants.AWS_REGION` takes precedence over other configs so that it doesn't break existing use-cases.


Thanks for this suggestion! Would you be willing to submit a PR?

**Comment by singhbaljit** [comment]
Yes, I can do that, but I'm new to this repo, so I can use some help. I'm thinking that we can add this functionality in [`GlueSchemaRegistryConfiguration#validateAndSetAWSRegion`](https://github.com/awslabs/aws-glue-schema-registry/blob/master/common/src/main/java/com/amazonaws/services/schemaregistry/common/configs/GlueSchemaRegistryConfiguration.java#L149). Basically,  after the `if` statement, try to use the the default region provider chain. I'm thinking of using [DefaultAwsRegionProviderChain](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/regions/providers/DefaultAwsRegionProviderChain.html) from AWS SDK v2. Please confirm this approach before I make a PR.
